### ISSUE TITLE
Add some method to get a summary of all properties 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/pubchem#15]
I'm not sure what the best choice here is and how we can implement this without being too redundant...

-  maybe we can just enumerate all getters? 
- or should we dynamically create all getters? As in https://stackoverflow.com/questions/377716/javascript-automatic-getter-setters-john-resig-book 
- or should we use a Proxy? 

because having to call a function in two different places will make things a bit hard to maintain

**Comment by kjappelbaum** [comment]
test `toJson` on the compoundData

**Comment by kjappelbaum** [comment]
ok, probably boils down to implement our own toJson https://stackoverflow.com/questions/42107492/json-stringify-es6-class-property-with-getter-setter

**Comment by lpatiny** [comment]
toJSON was added
