### ISSUE TITLE
Split predicted info and experimental data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/pubchem#17]
Everything that is Predicted should only be accessible from Compound.

Experimental data and other supplied information should go in CompoundData (that could be renamed if we find a better name).

For experimental data we can always provide a property summary and options to have the detailed information.

If we have the boiling point we would add 2 properties:
- boilingPoint that returns getBoilingPoint({returnDetails: false}).summary
- getBoilingPoint{{returnDetails:true} ) that returns by default the object that contains all the details

I think that if we call the property (boilingPoint) we should get the value of summary and if we call the method (getBoilingPoint) by default we receive everything (if we wanted the summary we would have call the property).

**Comment by kjappelbaum** [comment]
ok the only thing is that we will still need to get `CompoundData` as some predicted data such as complexity are in this json.
