### ISSUE TITLE
LCSS from pubchem

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/pubchem#24]
Pubchem provides a summary per compound about safety information. 

https://pubchemblog.ncbi.nlm.nih.gov/2015/08/17/a-laboratory-chemical-safety-summary-lcss-now-available-in-pubchem/

Those are data that we should parse as well. Maybe at the level of compound and not compoundData. Maybe this is what we need to present to the user.

https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/887/JSON?toc=LCSS+TOC

**Comment by lpatiny** [comment]
@kjappelbaum Could you have a look to this ? Seems there is the information PEER REVIEWED that is valuable and I don't know how it compares with what we have currently in CompoundData ghs / getGHS

**Comment by kjappelbaum** [comment]
I'm not sure the `PEER REVIEWED` helps that much as almost every reference has this attribute

**Comment by kjappelbaum** [comment]
I think we now implement this
