### ISSUE TITLE
Dealing with multiple GHS suppliers

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/pubchem#5]
Currently the getGHS yields to duplicates if many suppliers provide the same information.

I guess we should provide a more complex object that contains a 'summary' and then 'detailed' information in which we have the reference + the information

**Comment by lpatiny** [comment]
Maybe all all our methods should have options
`getGHS (options={})`

By default we would retrieve all the data with references but is there is the option `overview: true` we would somehow combine the data.

For bp, mp, etc it could be average values.
For safety it would be a join of all the values.

**Comment by kjappelbaum** [comment]
>we would somehow combine the data.

yes, we could just regex and then return the set of all H/P statements as the overview (i feel that should be the default in the ELN) and then also provide an object with the GHS from different references

**Comment by lpatiny** [comment]
@kjappelbaum could you implement this ?

**Comment by kjappelbaum** [comment]
i now output something like
```
{
 pictograms: uniquePictograms,
    hCodes: uniqueHCodes,
    pCodes: uniquePCodes,
    detail: {
      pictograms: allPictograms,
      hCodes: allHCodes,
      pCodes: allPCodes,
      refences: references,
    }}
```
where the top levels are `Set()` to ensure we include all possible H/P/pictograms (better more than less?) and then the detail contains objects of the form 
```
pictograms = [{referenceNumber: 2
pictogram: GHS01
}]
```

I do I feel this could something that is generalizable, i.e., we could always have the `detail`. Are you fine with this approach?

**Comment by lpatiny** [comment]
Detail seem indeed the right approach

In detail I would group the data by referenceNumber. What do you think ?

**Comment by kjappelbaum** [comment]
ok, this is what I started on the weekend here https://github.com/kjappelbaum/pubchem/tree/ghs

will clean up and make a PR
